version: "3.7"

services:
  django:
    build: ./django
    restart: always
    command: gunicorn SAIS_API.wsgi:application --bind 0.0.0.0:8000 -t 300 --workers 4 --log-level=debug
    volumes:
      - ./django/:/usr/src/django/
      - static_volume:/usr/src/django/static
      - webapp:/usr/src/django/webapp
    expose:
      - 8000
    environment:
      - SECRET_KEY=secret_key
      - DJANGO_DEBUG=True
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=NGNvarvpZIpa8R88
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - BRANCH=tw-webapp
    depends_on:
      - db

  db:
    # postgres 12 has a problem where multiple processes spawn and dont quit
    image: postgres:11-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: NGNvarvpZIpa8R88

  pgadmin:
    restart: always
    image: dpage/pgadmin4:4.16
    links:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ca
      PGADMIN_DEFAULT_PASSWORD: Hl8q5XmFN2yV1VLU
      PGADMIN_LISTEN_PORT: 5555

  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-rc.1
    depends_on:
      - db
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:NGNvarvpZIpa8R88@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: eDfGfj041tHBYkX9

  nginx:
    build: ./nginx
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=tw-webapp.duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNS:?No DUCKDNS Token}
      - STAGING=false
    volumes:
      - webapp:/webapp
      - static_volume:/usr/src/django/static
      - /home/appdata/letsencrypt:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
      - graphql-engine

volumes:
  webapp:
  static_volume:
  postgres_data:
